// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLe0wOt-islX8JcXczoJE3BLrQb2J9tu0',
    appId: '1:1096269841053:web:2d0fc8dd4d589972ecca74',
    messagingSenderId: '1096269841053',
    projectId: 'pushnotification-afa2f',
    authDomain: 'pushnotification-afa2f.firebaseapp.com',
    storageBucket: 'pushnotification-afa2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLwHMnuoVoNvREgZsCZvohs6eojeOAuuk',
    appId: '1:1096269841053:android:ee2f65f012e7bec1ecca74',
    messagingSenderId: '1096269841053',
    projectId: 'pushnotification-afa2f',
    storageBucket: 'pushnotification-afa2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QRw1Ig7r3t0a_pxxUyLnqAxW98K3Vmo',
    appId: '1:1096269841053:ios:4011135182f0f001ecca74',
    messagingSenderId: '1096269841053',
    projectId: 'pushnotification-afa2f',
    storageBucket: 'pushnotification-afa2f.firebasestorage.app',
    iosBundleId: 'com.example.smartyfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1QRw1Ig7r3t0a_pxxUyLnqAxW98K3Vmo',
    appId: '1:1096269841053:ios:4011135182f0f001ecca74',
    messagingSenderId: '1096269841053',
    projectId: 'pushnotification-afa2f',
    storageBucket: 'pushnotification-afa2f.firebasestorage.app',
    iosBundleId: 'com.example.smartyfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLe0wOt-islX8JcXczoJE3BLrQb2J9tu0',
    appId: '1:1096269841053:web:ee1b9fb39becb07becca74',
    messagingSenderId: '1096269841053',
    projectId: 'pushnotification-afa2f',
    authDomain: 'pushnotification-afa2f.firebaseapp.com',
    storageBucket: 'pushnotification-afa2f.firebasestorage.app',
  );
}
